### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by Prosta4okua** [smanschi/ros_web_gui#1]
i've installed via pip, but command `ros_web_gui` doesn't exist. Could you help?

**Comment by smanschi** [comment]
Hm which OS? I just installed it and it seems to be working.

**Comment by Prosta4okua** [comment]
> Hm which OS? I just installed it and it seems to be working.

WSL2 with Ubuntu 20.04. Maybe I'm just missing something

**Comment by Prosta4okua** [comment]
Oof, sorry, I just needed to restart terminal
